name = "FlexUnits"
uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
version = "0.2.9"
authors = ["Ruben Gonzalez <ruben.carbonbased@gmail.com> and contributors"]

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
FlexUnitfulExt = "Unitful"

[compat]
Test = "1.10"
Unitful = "1.27.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
